"""The Autism Spectrum Quotient (AQ) for Adult page."""

from practice.templates import template

import reflex as rx

@template(route="/aq_adult/scale", title="AQ Adult Scale")
def aq_adult_scale() -> rx.Component:
    return rx.flex(
        rx.flex(
            rx.text("成人自閉症狀量表", size="7", weight="bold"),
            rx.heading("Autism Spectrum Quotient (AQ) for Adult", size="7", weight="light"),
            rx.link(rx.button("返回首頁"), href="/"),
            direction="column",
            align="center",
            justify="center",
            width="100%",
        ),
        rx.flex(
            rx.text("請仔細閱讀每一個敘述，並請在右側適當的□勾選您認為最適合的答案。"),
            rx.text("不用花很多時間在問題上，但請您快速並誠實的回答。"),
            direction="column",
            width="100%",
            padding="10px 40px",
            align="center",
        ),
        rx.table.root(
            rx.table.header(
                rx.table.row(
                    rx.table.column_header_cell(""),
                    rx.table.column_header_cell("完全同意"),
                    rx.table.column_header_cell("稍微同意"),
                    rx.table.column_header_cell("稍微不同意"),
                    rx.table.column_header_cell("完全不同意"),
                ),
            ),
            rx.table.body(
                rx.table.row(
                    rx.table.row_header_cell("1. 我比較喜歡與人共事，而不是獨自工作。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("2. 我喜歡一再地用相同的方法做事。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("3. 如果我嘗試去想像某件事物，可以很輕易地在腦中浮現圖像。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("4. 我經常因為被一件事物強烈吸引，以致於忽略了其他的事物。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("5. 我經常注意到別人沒注意到的微小聲響。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("6. 我時常會注意車牌號碼、或類似的一串訊息。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("7. 雖然我覺得我所說的話是禮貌的，但其他人仍然經常告訴我，我說的話不太禮貌。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("8. 當我閱讀故事時，可以很輕易地想像書中角色的模樣。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("9. 我對日期著迷。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("10. 在一個社交團體中，我可以輕鬆地跟上幾個不同人的對話。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("11. 我在社交場合中覺得輕鬆自在。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("12. 我傾向於去注意別人不會注意的細節。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("13. 我寧願去圖書館，而不去派對。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("14. 我覺得編故事是容易的。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("15. 我覺得自己更容易被人、而非事物所吸引。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("16. 我容易產生非常強烈的興趣，當我不能投入去作的時候，我就會心煩不高興。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("17. 我喜歡社交閒談。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("18. 當我說話時，別人常不容易插話。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("19. 我對數字著迷。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("20. 當我閱讀故事時，我覺得很難猜測出書中角色的意圖。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("21. 我不會特別喜歡閱讀小說。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("22. 我發現要交新朋友是很困難的。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("23. 我總是會注意到事物當中的樣式類型。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("24. 我寧願去電影院，而不去博物館。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("25. 當我每日的例行作息被打亂時，我不會心煩不高興。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("26. 我常發現我不知道如何讓對話持續下去。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("27. 當別人跟我說話時，我覺得要了解其中的弦外之音是容易的。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("28. 我經常比較專注於整體，而不是小細節。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("29. 我不擅於記住電話號碼。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("30. 我經常不能注意到環境中，或是別人外觀上的小變化。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("31. 我知道如何分辨正在聽我說話的人是否感到無趣。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("32. 我覺得同時作超過一件以上的事情是容易的。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("33. 當我在講電話時，我不確定何時輪到我開口。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("34. 我喜歡自動自發地做事情。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("35. 我通常是最後一個知道笑話中笑點的人。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("36. 我發現僅由看對方的臉、就弄清楚他們在想什麼或有什麼感覺是容易的。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("37. 假如被打斷，我也可以很快地回到剛剛正在做的事。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("38. 我很擅於社交閒談。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("39. 人們常說我一直都在做同一件事。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("40. 當我年紀還小時，我樂於和其他孩子一起玩假扮的遊戲。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("41. 我喜歡收集關於事物分類的資訊（例如：汽車、鳥、火車、植物的種類等。）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("42. 我很難想像自己變成另外一個人會是什麼樣子。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("43. 我喜歡小心地計畫任何我所參與的活動。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("44. 我享受社交場合。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("45. 我覺得要弄清楚別人的意圖是困難的。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("46. 新的情境令我焦慮。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("47. 我喜歡認識新的人。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("48. 我是個擅於交際的人。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("49. 我不是很擅長記得別人的生日。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("50. 我覺得和小孩子玩假扮的遊戲是很容易的。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
            ),
        ),
        rx.flex(
            rx.link(rx.button("完成"), href="/"),
            margin="20px 0",
            justify="center",
            align="center",
        ),
        direction="column",
        width="100%",
        padding="10px 30px",

    )



@template(route="/aq_children/scale", title="AQ Children Scale")
def aq_children_scale() -> rx.Component:
    return rx.flex(
        rx.flex(
            rx.text("兒童自閉症狀量表", size="7", weight="bold"),
            rx.heading("Autism Spectrum Quotient (AQ) for Children", size="7", weight="light"),
            rx.link(rx.button("返回首頁"), href="/"),
            direction="column",
            align="center",
            justify="center",
            width="100%",
        ),
        rx.flex(
            rx.text("請仔細閱讀每一個敘述，並請在右側適當的□勾選您認為最適合描述您的孩子的答案。 "),
            direction="column",
            width="100%",
            padding="10px 40px",
            align="center",
        ),
        rx.table.root(
            rx.table.header(
                rx.table.row(
                    rx.table.column_header_cell(""),
                    rx.table.column_header_cell("完全同意"),
                    rx.table.column_header_cell("稍微同意"),
                    rx.table.column_header_cell("稍微不同意"),
                    rx.table.column_header_cell("完全不同意"),
                    justify="center",
                ),
            ),
            rx.table.body(
                rx.table.row(
                    rx.table.row_header_cell("1. 他／她喜歡跟別人合作，而不是獨立做事情。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    align="center",
                ),
                rx.table.row(
                    rx.table.row_header_cell("2. 他／她喜歡一而再、再而三地用一模一樣的方式做事情。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("3. 當他／她試著想像某個東西時，很容易在腦中創造出畫面。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("4. 他／她經常太強烈地投入於一件事，而忽略了其他的事物。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("5. 他／她經常注意到別人沒注意到的細微聲響。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("6. 他／她常注意到門牌號碼、或類似的一串資訊。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("7. 他／她無法理解怎樣叫做「有禮貌的行為」。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("8. 閱讀故事時，他／她很容易就可以想像故事人物長甚麼樣子。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("9. 他／她對日期著迷（他／她很喜歡與日期有關的事物）。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("10. 在社交團體中，他／她可以輕鬆地跟上和幾個不同人的對話。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("11. 他／她在社交場合中覺得輕鬆自在。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("12. 他／她容易注意到別人沒察覺到的細節。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("13. 比起參加慶生會，他／她還比較喜歡去圖書館。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("14. 編故事對他／她而言很容易。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("15. 他／她對人的興趣超過對事物的興趣。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("16. 他／她容易有非常強烈的興趣，而當他／她不能投入去做感興趣的事情時，就會不高興。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("17. 他／她喜愛社交閒談。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("18. 當他／她說話時，別人不容易插得上話。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("19. 他／她對數字著迷（他／她很喜歡與數字有關的事物）。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("20. 閱讀故事的時候，他／她很難了解故事人物的意圖或感覺。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("21. 他／她並不特別喜歡閱讀故事書。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("22. 交新朋友對他／她而言很困難。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("23. 他／她總是會注意到事物之中存在的規則。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("24. 比起博物館，他／她比較喜歡去電影院。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("25. 即使每天固定的生活作息被打亂了，他／她也不會不高興。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("26. 他／她不知道如何持續與同學間的對話。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("27. 和別人說話的時候，他／她能輕易地察覺對方的言外之意。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("28. 他／她通常比較專注於整體，而非小細節。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("29. 他／她不擅長記住電話號碼。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("30. 他／她通常不會注意到環境中或別人外表的小變化。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("31. 他／她知道如何分辨正在聽他／她說話的人是否漸漸感到無聊。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("32. 在不同的活動間轉換，對他／她而言很容易。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("33. 講電話時，他／她不太確定什麼時候該輪到他／她接話。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("34. 他／她喜歡自動自發地做事情。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("35. 他／她經常是最後一個理解笑話笑點的人。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("36. 他／她可以輕易地只從別人的臉部表情就了解他們的想法或感覺。 "),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("37. 假如被打斷，他／她可以很快地回到剛剛正在做的事情。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("38. 他／她善於社交閒談。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("39. 別人常跟他／她說他／她總是一直講同樣的事情。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("40. 幼稚園時，他／她喜歡和其他小朋友玩有假裝性質的遊戲（例如：扮家家酒）。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("41. 他／她喜歡蒐集關於事物類別的資訊（例如：車子的種類、鳥的種類、火車的類型、植物的類別等等）。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("42. 他／她很難想像如果自己變成另外一個人會是什麼樣子。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("43. 他／她喜歡仔細規劃他／她所參與的任何一項活動。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("44. 他／她喜歡社交場合。 "),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("45. 瞭解別人的意圖對他／她而言很困難。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("46. 新的情境（狀況）令他／她焦慮。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("47. 他／她喜歡認識新的人。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("48. 他／她善於顧及別人的感受，避免讓他人感覺受傷。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("49. 他／她不擅長記住別人的生日。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("50. 跟別的小朋友玩有假裝性質的遊戲，對他／她而言非常容易。"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
            ),
        ),
        rx.flex(
            rx.link(rx.button("完成"), href="/"),
            margin="20px 0",
            justify="center",
            align="center",
        ),

        direction="column",
        width="100%",
        padding="10px 30px",

    )