"""The SNAP-IV Questionnaire."""

from practice.templates import template

import reflex as rx


@template(route="/snap4/scale_adult", title="SNAP-IV Scale_Adult")
def snap4_scale_adult() -> rx.Component:
    return rx.flex(
        rx.flex(
            rx.text("注意力缺陷過動症量表", size="7", weight="bold"),
            rx.heading("SNAP-IV Questionnaire", size="7", weight="light"),
            rx.heading("Self Report ver.", size="5", weight="light"),
            rx.flex(
                rx.link(rx.button("返回首頁"), href="/"),
                rx.link(rx.button("SNAP-IV 首頁"), href="/snap4"),
                width="350px",
                justify="between",
                align="baseline",
            ),
            
            direction="column",
            align="center",
            justify="center",
            width="100%",
        ),
        rx.flex(
            rx.text("請圈選最符合你在小學時(六到十二歲時)情形的代碼"),
            direction="column",
            width="100%",
            padding="10px 40px",
            align="center",
        ),
        rx.table.root(
            rx.table.header(
                rx.table.row(			
                    rx.table.column_header_cell(""),
                    rx.table.column_header_cell("完全沒有"),
                    rx.table.column_header_cell("有一點點"),
                    rx.table.column_header_cell("還算不少"),
                    rx.table.column_header_cell("非常的多"),
                ),
            ),
            rx.table.body(
                rx.table.row(
                    rx.table.row_header_cell("1. 在做學校作業或其他的活動時，無法專注於細節的部份或出現粗心的錯誤"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("2. 很難持續專注於工作或遊戲活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("3. 看起來好像沒有在聽別人對他（她）說話的內容"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("4. 沒有辦法遵循指示，也無法完成學校作業或家事 （並不是由於對立性行為或無法了解指示的內容）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("5. 很難組織規劃工作及活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("6. 逃避，或表達不願意，或很難從事於需要持續性動腦的工作（例如學校作業或是家庭作業）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("7. 會弄丟作業或活動所必需的東西 （例如：學校作業、鉛筆、書、工具，或玩具）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("8. 很容易受外在刺激影響而分心"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("9. 在日常生活中忘東忘西的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("10. 在座位上玩弄手腳或不好好坐著"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("11. 在教室或是其他必須持續坐著的場合，會任意離開座位"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("12. 在不適當的場合，亂跑或爬高爬低"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("13. 很難安靜地玩或參與休閒活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("14. 總是一直在動或是像裝了馬達似的動個不停"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("15. 話很多"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("16. 在問題還沒問完前就急著回答"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("17. 在遊戲或團體活動中，很難排隊或輪流等待"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("18. 打斷或干擾別人 （例如 插嘴或打斷別人的遊戲）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("19. 發脾氣"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("20. 與大人爭論"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("21. 主動地反抗或拒絕大人的要求或規定"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("22. 故意地做一些事去干擾別人"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("23. 因自己犯的錯或不適當的行為而怪罪別人"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("24. 易怒的或很容易被別人激怒"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("25. 生氣的及怨恨的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("26. 惡意的或有報復心的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
            ),
        ),
        rx.flex(
            rx.link(rx.button("完成"), href="/"),
            margin="20px 0",
            justify="center",
            align="center",
        ),
        direction="column",
        width="100%",
        padding="10px 30px",

    )
@template(route="/snap4/scale_child", title="SNAP-IV Scale_Chlid")
def snap4_scale_child() -> rx.Component:
    return rx.flex(
        rx.flex(
            rx.text("注意力缺陷過動症量表", size="7", weight="bold"),
            rx.heading("SNAP-IV Questionnaire", size="7", weight="light"),
            rx.heading("Chlid ver.", size="5", weight="light"),
            rx.flex(
                rx.link(rx.button("返回首頁"), href="/"),
                rx.link(rx.button("SNAP-IV 首頁"), href="/snap4"),
                width="350px",
                justify="between",
                align="baseline",
            ),
            
            direction="column",
            align="center",
            justify="center",
            width="100%",
        ),
        rx.flex(
            rx.text("請圈選最符合你過去一星期狀況的代碼"),
            direction="column",
            width="100%",
            padding="10px 40px",
            align="center",
        ),
        rx.table.root(
            rx.table.header(
                rx.table.row(			
                    rx.table.column_header_cell(""),
                    rx.table.column_header_cell("完全沒有"),
                    rx.table.column_header_cell("有一點點"),
                    rx.table.column_header_cell("還算不少"),
                    rx.table.column_header_cell("非常的多"),
                ),
            ),
            rx.table.body(
                rx.table.row(
                    rx.table.row_header_cell("1. 在做學校作業或其他的活動時，無法專注於細節的部份或出現粗心的錯誤"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("2. 很難持續專注於工作或遊戲活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("3. 看起來好像沒有在聽別人對他（她）說話的內容"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("4. 沒有辦法遵循指示，也無法完成學校作業或家事 （並不是由於對立性行為或無法了解指示的內容）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("5. 很難組織規劃工作及活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("6. 逃避，或表達不願意，或很難從事於需要持續性動腦的工作（例如學校作業或是家庭作業）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("7. 會弄丟作業或活動所必需的東西 （例如：學校作業、鉛筆、書、工具，或玩具）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("8. 很容易受外在刺激影響而分心"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("9. 在日常生活中忘東忘西的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("10. 在座位上玩弄手腳或不好好坐著"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("11. 在教室或是其他必須持續坐著的場合，會任意離開座位"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("12. 在不適當的場合，亂跑或爬高爬低"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("13. 很難安靜地玩或參與休閒活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("14. 總是一直在動或是像裝了馬達似的動個不停"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("15. 話很多"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("16. 在問題還沒問完前就急著回答"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("17. 在遊戲或團體活動中，很難排隊或輪流等待"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("18. 打斷或干擾別人 （例如 插嘴或打斷別人的遊戲）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("19. 發脾氣"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("20. 與大人爭論"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("21. 主動地反抗或拒絕大人的要求或規定"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("22. 故意地做一些事去干擾別人"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("23. 因自己犯的錯或不適當的行為而怪罪別人"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("24. 易怒的或很容易被別人激怒"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("25. 生氣的及怨恨的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("26. 惡意的或有報復心的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
            ),
        ),
        rx.flex(
            rx.link(rx.button("完成"), href="/"),
            margin="20px 0",
            justify="center",
            align="center",
        ),
        direction="column",
        width="100%",
        padding="10px 30px",

    )
@template(route="/snap4/scale_parents", title="SNAP-IV Scale_Parents")
def snap4_scale_parents() -> rx.Component:
    return rx.flex(
        rx.flex(
            rx.text("注意力缺陷過動症量表", size="7", weight="bold"),
            rx.heading("SNAP-IV Questionnaire", size="7", weight="light"),
            rx.heading("Parents ver.", size="5", weight="light"),
            rx.flex(
                rx.link(rx.button("返回首頁"), href="/"),
                rx.link(rx.button("SNAP-IV 首頁"), href="/snap4"),
                width="350px",
                justify="between",
                align="baseline",
            ),
            
            direction="column",
            align="center",
            justify="center",
            width="100%",
        ),
        rx.flex(
            rx.text("請圈選最能表達在您的孩子過去的一個星期的狀況"),
            direction="column",
            width="100%",
            padding="10px 40px",
            align="center",
        ),
        rx.table.root(
            rx.table.header(
                rx.table.row(			
                    rx.table.column_header_cell(""),
                    rx.table.column_header_cell("完全沒有"),
                    rx.table.column_header_cell("有一點點"),
                    rx.table.column_header_cell("還算不少"),
                    rx.table.column_header_cell("非常的多"),
                ),
            ),
            rx.table.body(
                rx.table.row(
                    rx.table.row_header_cell("1. 在做學校作業或其他的活動時，無法專注於細節的部份或出現粗心的錯誤"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("2. 很難持續專注於工作或遊戲活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("3. 看起來好像沒有在聽別人對他（她）說話的內容"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("4. 沒有辦法遵循指示，也無法完成學校作業或家事 （並不是由於對立性行為或無法了解指示的內容）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("5. 很難組織規劃工作及活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("6. 逃避，或表達不願意，或很難從事於需要持續性動腦的工作（例如學校作業或是家庭作業）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("7. 會弄丟作業或活動所必需的東西 （例如：學校作業、鉛筆、書、工具，或玩具）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("8. 很容易受外在刺激影響而分心"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("9. 在日常生活中忘東忘西的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("10. 在座位上玩弄手腳或不好好坐著"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("11. 在教室或是其他必須持續坐著的場合，會任意離開座位"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("12. 在不適當的場合，亂跑或爬高爬低"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("13. 很難安靜地玩或參與休閒活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("14. 總是一直在動或是像裝了馬達似的動個不停"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("15. 話很多"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("16. 在問題還沒問完前就急著回答"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("17. 在遊戲或團體活動中，很難排隊或輪流等待"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("18. 打斷或干擾別人 （例如 插嘴或打斷別人的遊戲）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("19. 發脾氣"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("20. 與大人爭論"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("21. 主動地反抗或拒絕大人的要求或規定"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("22. 故意地做一些事去干擾別人"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("23. 因自己犯的錯或不適當的行為而怪罪別人"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("24. 易怒的或很容易被別人激怒"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("25. 生氣的及怨恨的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("26. 惡意的或有報復心的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
            ),
        ),
        rx.flex(
            rx.link(rx.button("完成"), href="/"),
            margin="20px 0",
            justify="center",
            align="center",
        ),
        direction="column",
        width="100%",
        padding="10px 30px",

    )
@template(route="/snap4/scale_teacher", title="SNAP-IV Scale_Teacher")
def snap4_scale_teacher() -> rx.Component:
    return rx.flex(
        rx.flex(
            rx.text("注意力缺陷過動症量表", size="7", weight="bold"),
            rx.heading("SNAP-IV Questionnaire", size="7", weight="light"),
            rx.heading("Teacher ver.", size="5", weight="light"),
            rx.flex(
                rx.link(rx.button("返回首頁"), href="/"),
                rx.link(rx.button("SNAP-IV 首頁"), href="/snap4"),
                width="350px",
                justify="between",
                align="baseline",
            ),
            
            direction="column",
            align="center",
            justify="center",
            width="100%",
        ),
        rx.flex(
            rx.text("請圈選最能表達您的學生在過去的一個星期狀況的代碼"),
            direction="column",
            width="100%",
            padding="10px 40px",
            align="center",
        ),
        rx.table.root(
            rx.table.header(
                rx.table.row(			
                    rx.table.column_header_cell(""),
                    rx.table.column_header_cell("完全沒有"),
                    rx.table.column_header_cell("有一點點"),
                    rx.table.column_header_cell("還算不少"),
                    rx.table.column_header_cell("非常的多"),
                ),
            ),
            rx.table.body(
                rx.table.row(
                    rx.table.row_header_cell("1. 在做學校作業或其他的活動時，無法專注於細節的部份或出現粗心的錯誤"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("2. 很難持續專注於工作或遊戲活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("3. 看起來好像沒有在聽別人對他（她）說話的內容"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("4. 沒有辦法遵循指示，也無法完成學校作業或家事 （並不是由於對立性行為或無法了解指示的內容）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("5. 很難組織規劃工作及活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("6. 逃避，或表達不願意，或很難從事於需要持續性動腦的工作（例如學校作業或是家庭作業）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("7. 會弄丟作業或活動所必需的東西 （例如：學校作業、鉛筆、書、工具，或玩具）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("8. 很容易受外在刺激影響而分心"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("9. 在日常生活中忘東忘西的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("10. 在座位上玩弄手腳或不好好坐著"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("11. 在教室或是其他必須持續坐著的場合，會任意離開座位"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("12. 在不適當的場合，亂跑或爬高爬低"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("13. 很難安靜地玩或參與休閒活動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("14. 總是一直在動或是像裝了馬達似的動個不停"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("15. 話很多"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("16. 在問題還沒問完前就急著回答"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("17. 在遊戲或團體活動中，很難排隊或輪流等待"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("18. 打斷或干擾別人 （例如 插嘴或打斷別人的遊戲）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("19. 發脾氣"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("20. 與大人爭論"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("21. 主動地反抗或拒絕大人的要求或規定"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("22. 故意地做一些事去干擾別人"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("23. 因自己犯的錯或不適當的行為而怪罪別人"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("24. 易怒的或很容易被別人激怒"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("25. 生氣的及怨恨的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("26. 惡意的或有報復心的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
            ),
        ),
        rx.flex(
            rx.link(rx.button("完成"), href="/"),
            margin="20px 0",
            justify="center",
            align="center",
        ),
        direction="column",
        width="100%",
        padding="10px 30px",

    )