"""The SRS page."""

from practice.templates import template

import reflex as rx


@template(route="/srs/self_scale", title="SRS Self Scale")
def srs_self_scale() -> rx.Component:
    return rx.flex(
        rx.flex(
            rx.text("自陳式社會性反應量表", size="7", weight="bold"),
            rx.heading("Social Responsiveness Scale (SRS)", size="7", weight="light"),
            rx.heading("Self-Report ver.", size="5", weight="light"),
            rx.flex(
                rx.link(rx.button("返回首頁"), href="/"),
                rx.link(rx.button("SRS 首頁"), href="/srs"),
                width="350px",
                justify="between",
                align="baseline",
            ),
            direction="column",
            align="center",
            justify="center",
            width="100%",
        ),
        rx.flex(
            rx.text("說明：針對每一題，請圈選最能描述你在過去 6 個月內行為的項目。"),
            direction="column",
            width="100%",
            padding="10px 40px",
            align="center",
        ),
        rx.table.root(
            rx.table.header(
                rx.table.row(
                    rx.table.column_header_cell(""),
                    rx.table.column_header_cell("不符合"),
                    rx.table.column_header_cell("有些符合"),
                    rx.table.column_header_cell("經常符合"),
                    rx.table.column_header_cell("幾乎總是符合"),
                ),
            ),
            rx.table.body(
                rx.table.row(
                    rx.table.row_header_cell("1. 我感覺自己似乎在社交場合中比在獨處時更不自在"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("2. 別人認為我臉上的表情和我正在說的話並不相稱"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("3. 我在與他人互動時似乎是有自信的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("4. 我在有壓力時，會表現出在別人看來似乎怪異的固著或僵化行為模式"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("5. 我無法察覺到別人正想佔我便宜"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("6. 我寧願獨處而不願跟別人在一起"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("7. 我知道別人正在說的或感覺到的是什麼"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("8. 我的行為方式在別人眼中似乎是奇特或古怪的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("9. 我似乎太依賴別人來協助處理生活基本需要"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("10. 我感覺自己太依照字面理解事情，而不瞭解一段對話之中的真正含義"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("11. 我有很強的自信心"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("12. 我能對別人傳達我的情感"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("13. 我在與同儕一來一往互動時是笨拙的 （例如：似乎不瞭解對話所需的一來一往）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("14. 我的 （動作的）協調性是不好的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("15. 我能察覺別人說話聲調和臉部表情的變化，並作適當回應"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("16. 我會避開眼神接觸或有不尋常的眼神接觸"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("17. 我能辨認出某事是不公平的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("18. 我即使盡了最大努力，仍然有交朋友的困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("19. 我會因為在對話中無法讓自己的想法被順利理解而受挫"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("20. 我有不尋常的感官知覺興趣 （例如： 喜歡聞自己的手指）或重複以奇怪的方式玩弄手邊的東西"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("21. 我能在適當情境下模仿別人的動作或樣子"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("22. 我能和其他成人適切地互動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("23. 我不參與團體活動或社交場合，除非被要求這樣做"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("24. 我和其他人相比，要改變生活慣例更為困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("25. 我不大在意和別人格格不入或者「觀點不一致」"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("26. 當別人難過時會安慰他們"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("27. 我會避免由我開始啟動與同儕或大人的社交互動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("28. 我會一而再、再而三地想著或說著同樣的事"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("29. 我被別人認為是古怪或奇特的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("30. 我在有很多事情同時發生的情境下會變得心煩"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("31. 我一旦開始思考某件事情就無法不持續一直想它"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("32. 我有好的個人衛生"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("33. 我在社交上是笨拙的，就算是我試著要有禮貌時仍然如此"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("34. 我會迴避想在情感上接近我的人們"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("35. 跟上一般對話的節奏對我來說有困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("36. 我與家人相處有困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("37. 我與其他成人相處有困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("38. 我會適當地回應別人的心情改變 （例如：當朋友的心情從快樂變成難過時）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("39. 我在別人眼中有不尋常地狹窄的興趣範圍"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("40. 我是有想像力的，不會脫離現實"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("41. 我會漫無目標地從一個活動換過一個"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("42. 我似乎對聲音、質地 （觸感）、或氣味過度敏感"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("43. 我要與最親的親人分開是容易的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("44. 我不以和我同年齡的人相同的方式去瞭解事件之間是如何彼此相關 （因果關係）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("45. 我對旁邊的人所注意的事通常也感興趣"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("46. 我有過於嚴肅的臉部表情"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("47. 我會在不適當的時機大笑"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("48. 我有幽默感、聽得懂笑話"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("49. 我極為擅長一些知識性或計算的工作，但其他大部分的事情則沒有做得那麼好"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("50. 我有重複、古怪的行為"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("51. 我有困難直接回答問題，最後變成繞著主題談論"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("52. 當我講話太大聲或製造太多噪音時，自己會知道"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("53. 我會以別人認為不尋常的語調跟人談話 （例如：講話像個機器人、或像自己正在演講一樣）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("54. 我會把人們當成物品般地作出反應"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("55. 當我靠別人太近、或侵犯到別人的空間時，自己會知道"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("56. 我曾經從正在談話的兩個人中間走過去"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("57. 我很常被取笑"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("58. 我太專注事物的局部而不看全貌。例如，若被要求描述故事的情節，我可能只談到故事角色們所穿的衣服種類"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("59. 我感覺自己是過度多疑的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("60. 我在情感上是疏離的，不表現我的感受 "),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("61. 我感覺自己是僵化而沒有彈性的、不容易改變我的想法"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("62. 我用別人認為不尋常或不合邏輯的理由解釋自己所做的事"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("63. 我以不尋常的方式碰觸別人"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("64. 我在社交情境中太過緊張"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("65. 我會往半空中 （或地上或其他方向）漫無目的地盯視或凝望"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
            ),
        ),
        rx.flex(
            rx.link(rx.button("完成"), href="/"),
            margin="20px 0",
            justify="center",
            align="center",
        ),
        direction="column",
        width="100%",
        padding="10px 30px",

    )
@template(route="/srs/children_scale", title="SRS Children Scale")
def srs_children_scale() -> rx.Component:
    return rx.flex(
        rx.flex(
            rx.text("兒童社會性反應量表", size="7", weight="bold"),
            rx.heading("Social Responsiveness Scale (SRS) for Children", size="7", weight="light"),
            rx.heading("Children ver.", size="5", weight="light"),
            rx.flex(
                rx.link(rx.button("返回首頁"), href="/"),
                rx.link(rx.button("SRS 首頁"), href="/srs"),
                width="350px",
                justify="between",
                align="baseline",
            ),
            direction="column",
            align="center",
            justify="center",
            width="100%",
        ),
        rx.flex(
            rx.text("說明：針對每一題，請圈選最能描述此兒童在過去 6 個月內行為的項目。"),
            direction="column",
            width="100%",
            padding="10px 40px",
            align="center",
        ),
        rx.table.root(
            rx.table.header(
                rx.table.row(
                    rx.table.column_header_cell(""),
                    rx.table.column_header_cell("不符合"),
                    rx.table.column_header_cell("有些符合"),
                    rx.table.column_header_cell("經常符合"),
                    rx.table.column_header_cell("幾乎總是符合"),
                ),
            ),
            rx.table.body(
                rx.table.row(
                    rx.table.row_header_cell("1. 似乎在社交場合中比在獨處時更為坐立不安"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("2. 他臉上的表情和他正在說的話並不相稱"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("3. 在與他人互動時似乎是有自信的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("4. 有壓力下，他表現出似乎很怪異的固著或僵化行為模式"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("5. 無法察覺到別人正想佔他便宜"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("6. 寧願獨處而不跟別人在一起"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("7. 知道別人正在說的或感覺到的是什麼"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("8. 行為方式似乎是奇特或古怪的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("9. 黏著大人，似乎太依賴他們"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("10. 太依照字面理解事情，而不瞭解一段對話之中的真正含義"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("11. 有很強的自信心"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("12. 能對別人傳達他的情感"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("13. 在與同儕一來一往互動時是笨拙的（例如：似乎不瞭解對話所需的一來一往）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("14. （動作的）協調性是不好的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("15. 能瞭解其他人的聲調和臉部表情的含義"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("16. 避開眼神接觸或有不尋常的眼神接觸"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("17. 能辨認出某事是不公平的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("18. 即使當他盡了最大努力，仍然有交朋友的困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("19. 會因為在對話中無法讓自己的想法被順利理解而受挫"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("20. 顯現不尋常的感官知覺興趣（例如：喜歡用嘴含東西、或旋轉物品）或以奇怪的方式玩玩具"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("21. 能模仿別人的動作"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("22. 和同齡孩子適當地玩在一起"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("23. 不參加團體活動，除非被要求這樣做"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("24. 和其他孩子相比，要改變生活慣例更為困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("25. 似乎不在意和別人格格不入或者「觀點不一致」"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("26. 當別人難過時會安慰他們"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("27. 避免由他開始啟動與同儕或大人的社交互動"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("28. 一而再、再而三地想著或說著同樣的事"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("29. 被別的孩子認為是古怪或奇特的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("30. 在有很多事情同時發生的情境下會變得心煩"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("31. 他一旦開始思考某件事情就無法不持續一直想它"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("32. 有好的個人衛生"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("33. 在社交上是笨拙的，就算是他試著要有禮貌時仍是這樣"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("34. 迴避想在情感上接近他的人們"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("35. 跟上一般對話的節奏對他來說有困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("36. 與大人相處有困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("37. 與同儕相處有困難"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("38. 適當地回應別人的心情改變（例如：當朋友或玩伴的心情從快樂變成難過時）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("39. 有不尋常地狹窄的興趣範圍"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("40. 是有想像力的、善於假裝的（但沒有失去與現實的接觸）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("41. 無目標地從一個活動遊移到另外一個"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("42. 似乎對聲音、質地（觸感）、或氣味過度敏感"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("43. 要與照顧者分開是容易的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("44. 不用與其他同齡孩子相同的方式去瞭解事件之間是如何彼此相關（因果關係）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("45. 會集中他的注意力在別人正在注視或聆聽的地方"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("46. 有過於嚴肅的臉部表情"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("47. 是傻呼呼的、或者會不適當地大笑"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("48. 有幽默感、聽得懂笑話"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("49. 把一些事情做得極端地好，但其他大部分的事情則沒有做得那麼好"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("50. 有重複、古怪的行為，例如重複拍動手掌或搖擺身體"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("51. 有困難直接回答問題，最後變成繞著主題談論"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("52. 當他講話太大聲或製造太多噪音時，自己會知道"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("53. 以不尋常的語調跟人談話（例如：講話像個機器人、或像自己正在演講一樣）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("54. 似乎把人們當成物品般地作出反應"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("55. 當他靠某人太近、或侵犯到某人的空間時，自己會知道"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("56. 從正在談話的兩個人中間走過去"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("57. 很常被戲弄"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("58. 太專注事物的局部而不看全貌。例如，若被要求描述在某個故事中發生了什麼，他可能只談故事人物所穿的衣服種類"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("59. 是過度多疑的"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("60. 在情感上是疏離的，不展現他的感受"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("61. 是僵化而沒有彈性的、不容易改變他的想法"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("62. 用不尋常或不合邏輯的理由解釋他所做的事"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("63. 以不尋常的方式碰觸別人（例如：他可能只是為了接觸或聯繫而碰觸某人，然後沒說什麼就走開）"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("64. 在社交情境中太過緊張"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
                rx.table.row(
                    rx.table.row_header_cell("65. 往半空中（或地上或其他方向）漫無目的地盯視或凝望"),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                    rx.table.cell(rx.checkbox()),
                ),
            ),
        ),
        rx.flex(
            rx.link(rx.button("完成"), href="/"),
            margin="20px 0",
            justify="center",
            align="center",
        ),
        direction="column",
        width="100%",
        padding="10px 30px",

    )
